	CREATE DATABASE hotelMCP;
	USE hotelMCP;

	CREATE TABLE clienteMCP (
		idCliente INT PRIMARY KEY AUTO_INCREMENT,
		nombre VARCHAR(50) NOT NULL,
		apellidos VARCHAR(100) NOT NULL,
		email VARCHAR(100) NOT NULL UNIQUE,
		dni VARCHAR(15) NOT NULL UNIQUE,
		clave VARCHAR(100) NOT NULL
	);
    
    SELECT * FROM clienteMCP;